"use client";
import { FormEvent, useState } from "react";
import { parseEther } from "ethers";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { useApp, isLocal } from "../../../components/providers";
import { Button, Card, Eyebrow } from "../../../components/ui";
import { getContract } from "../../../lib/contract";
import { decodeRevert, isValidAddress } from "../../../lib/web3";
import { addDemoActivity, DEMO_ADDRESSES, nextDemoJobId, saveDemoJob, saveJobMeta } from "../../../lib/demo";

type Phase="idle"|"confirming"|"submitted"|"mined"|"failed";
export default function NewJob(){
  const {demo,address,provider,chainId}=useApp();const router=useRouter();
  const [form,setForm]=useState({title:"Community Hall Renovation",company:"Sri Buildworks",description:"Assist with renovation work, material movement and general site support for a community hall.",jobType:"Construction",workers:"2",duration:"6 days",location:"Perungalathur, Chennai",wage:demo?"8500":"0.01",worker:demo?DEMO_ADDRESSES.worker:"",supervisor:demo?DEMO_ADDRESSES.supervisor:"",timeout:"60",requirements:"Basic construction experience\nAvailable for the full job duration\nReport to site on time"});
  const [phase,setPhase]=useState<Phase>("idle"),[error,setError]=useState(""),[tx,setTx]=useState(""),[jobId,setJobId]=useState("");
  const update=(k:string,v:string)=>setForm(f=>({...f,[k]:v}));
  const submit=async(e:FormEvent)=>{e.preventDefault();setError("");
    if(!form.title.trim()||!form.description.trim()||!form.location.trim())return setError("Fill in the job title, description and location.");
    if(Number(form.wage)<=0||Number(form.timeout)<=0)return setError("Wage and timeout must be greater than zero.");
    if(!demo&&(!isValidAddress(form.worker)||!isValidAddress(form.supervisor)))return setError("Worker and supervisor must be valid wallet addresses.");
    if(demo){const id=nextDemoJobId(),timestamp=Math.floor(Date.now()/1000);const meta={id,title:form.title,company:form.company,description:form.description,jobType:form.jobType,workersRequired:Number(form.workers)||1,duration:form.duration,location:form.location,requirements:form.requirements.split("\n").map(x=>x.trim()).filter(Boolean),wageDisplay:`₹${Number(form.wage).toLocaleString("en-IN")}`,createdAt:timestamp};saveJobMeta(meta);saveDemoJob({...meta,contractor:DEMO_ADDRESSES.contractor,worker:form.worker,supervisor:form.supervisor,wageAmount:form.wage,completionTimeout:Number(form.timeout),claimedAt:0,proofHash:"0x"+"0".repeat(64),state:0,txHash:"0xdemo"+Date.now().toString(16)});addDemoActivity(id,{label:"JobPosted",detail:`Contractor posted job #${id}`,timestamp,type:"job"});setJobId(id);setPhase("mined");return;}
    if(!address||!provider||!isLocal(chainId))return setError("Connect MetaMask to the local Hardhat network.");
    try{const c=getContract(await provider.getSigner());setPhase("confirming");const tx1=await c.postJob(form.worker,form.supervisor,parseEther(form.wage),BigInt(form.timeout));setTx(tx1.hash);setPhase("submitted");const receipt=await tx1.wait();if(!receipt)throw new Error("Job transaction was not mined.");const event=receipt.logs.map((l:any)=>{try{return c.interface.parseLog(l)}catch{return null}}).find((x:any)=>x?.name==="JobPosted");const id=event?.args?.jobId?.toString();if(!id)throw new Error("JobPosted event not found.");const meta={id,title:form.title,company:form.company,description:form.description,jobType:form.jobType,workersRequired:Number(form.workers)||1,duration:form.duration,location:form.location,requirements:form.requirements.split("\n").map(x=>x.trim()).filter(Boolean),createdAt:Math.floor(Date.now()/1000)};saveJobMeta(meta);setJobId(id);setPhase("mined");router.push(`/jobs/${id}`);}catch(e:any){setError(decodeRevert(e));setPhase("failed");}
  };
  return <main className="page"><div className="container max-w-5xl"><div className="form-heading"><div><Eyebrow>POST A JOB</Eyebrow><h1 className="page-title">Create a protected job.</h1><p>Describe the work first. Wagely then records the worker, supervisor, wage and contract timeout on-chain.</p></div><Link href="/jobs" className="back-link">← Find jobs</Link></div>
    <form onSubmit={submit} className="form-layout"><Card><div className="form-section"><Eyebrow>JOB DETAILS</Eyebrow><div className="form-grid two"><Field label="Job title"><input value={form.title} onChange={e=>update("title",e.target.value)} placeholder="e.g. Site Helper"/></Field><Field label="Company / contractor name"><input value={form.company} onChange={e=>update("company",e.target.value)} placeholder="Company name"/></Field><Field label="Job type"><select value={form.jobType} onChange={e=>update("jobType",e.target.value)}><option>Construction</option><option>Masonry</option><option>Electrical</option><option>General Labour</option><option>Painting</option><option>Plumbing</option></select></Field><Field label="Workers required"><input type="number" min="1" value={form.workers} onChange={e=>update("workers",e.target.value)}/></Field><Field label="Duration"><input value={form.duration} onChange={e=>update("duration",e.target.value)} placeholder="e.g. 10 days"/></Field><Field label="Location"><input value={form.location} onChange={e=>update("location",e.target.value)} placeholder="Chennai"/></Field><div className="field full"><label>Job description</label><textarea rows={5} value={form.description} onChange={e=>update("description",e.target.value)}/></div><div className="field full"><label>Requirements <span>one per line</span></label><textarea rows={4} value={form.requirements} onChange={e=>update("requirements",e.target.value)}/></div></div></div></Card>
    <Card><div className="form-section"><Eyebrow>ESCROW SETUP</Eyebrow><div className="form-grid"><Field label={demo?"Wage (demo ₹)":"Escrow amount (local ETH)"}><input inputMode="decimal" value={form.wage} onChange={e=>update("wage",e.target.value)}/></Field><Field label="Completion timeout (seconds)"><input type="number" min="1" value={form.timeout} onChange={e=>update("timeout",e.target.value)}/></Field><Field label="Worker wallet address"><input value={form.worker} onChange={e=>update("worker",e.target.value)} placeholder="0x…"/></Field><Field label="Supervisor wallet address"><input value={form.supervisor} onChange={e=>update("supervisor",e.target.value)} placeholder="0x…"/></Field></div><div className="contract-note"><b>What goes on-chain</b><p>Worker, supervisor, escrow amount and completion timeout are stored by WageEscrow. The title, company, location and other job-page details are kept as frontend metadata because the supplied contract does not store those fields.</p></div></div><div className="form-footer"><Button type="submit" loading={phase==="confirming"||phase==="submitted"}>{demo?"Create demo job":"Post job & continue"}</Button></div></Card></form>
    {error&&<div className="alert error mt-5">{error}</div>}{phase==="submitted"&&<div className="alert success mt-5">Transaction submitted: <span className="mono">{tx.slice(0,12)}…</span></div>}{phase==="mined"&&jobId&&<div className="success-panel"><div><Eyebrow>JOB CREATED</Eyebrow><h2>Job #{jobId} is ready.</h2><p>{demo?"This is a presentation job stored in the browser.":"The contract transaction has been mined. Your job metadata is attached locally to this browser."}</p></div><Link className="btn btn-primary" href={`/jobs/${jobId}`}>View job →</Link></div>}
  </div></main>
}
function Field({label,children}:{label:string;children:React.ReactNode}){return <div className="field"><label>{label}</label>{children}</div>}
