"use client";
import { useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { useApp, isLocal } from "../../components/providers";
import { Card, EmptyState, Eyebrow, JobCard } from "../../components/ui";
import { DEMO_ADDRESSES, getDemoJobs, getJobMeta } from "../../lib/demo";
import { getContract } from "../../lib/contract";

const roles=["Worker","Contractor"] as const;type Role=typeof roles[number];
async function loadJobs(provider:any){const c=getContract(provider);const logs=await c.queryFilter(c.filters.JobPosted(),0,"latest");const rows=await Promise.all(logs.map(async(log:any)=>{const p=c.interface.parseLog(log);if(!p)return null;const id=p.args.jobId.toString(),j=await c.getJob(id);return {id,contractor:j[0],worker:j[1],supervisor:j[2],wageAmount:j[3],completionTimeout:j[4],claimedAt:j[5],proofHash:j[6],state:Number(j[7]),txHash:log.transactionHash};}));return rows.filter(Boolean).reverse();}
export default function Dashboard(){const {demo,address,provider,chainId}=useApp();const [role,setRole]=useState<Role>("Worker"),[jobs,setJobs]=useState<any[]>([]),[error,setError]=useState("");useEffect(()=>{const r=localStorage.getItem("wagely-dashboard-role") as Role|null;if(r) setRole(r)},[]);useEffect(()=>{const load=async()=>{try{if(demo){setJobs(getDemoJobs());return;}if(!provider||!isLocal(chainId)){setJobs([]);return;}setJobs(await loadJobs(provider));}catch(e:any){setError(e?.shortMessage||e?.message||"Could not load jobs.")}};load();const t=setInterval(load,4000);return()=>clearInterval(t)},[demo,provider,chainId]);const choose=(r:Role)=>{setRole(r);localStorage.setItem("wagely-dashboard-role",r);window.dispatchEvent(new CustomEvent("wagely-demo-role-updated"))};const target=demo?(role==="Worker"?DEMO_ADDRESSES.worker:DEMO_ADDRESSES.contractor):address;const relevant=jobs.filter(j=>target&&String(j[role==="Worker"?"worker":"contractor"]).toLowerCase()===target.toLowerCase());const stats=useMemo(()=>({active:relevant.filter(j=>[1,2,3].includes(j.state)).length,completed:relevant.filter(j=>j.state===4).length,claimed:relevant.filter(j=>j.state===3).length,funded:relevant.filter(j=>j.state===1).length}),[relevant]);return <main className="page dashboard-page"><div className="container"><section className={`dashboard-hero ${role.toLowerCase()}`}><div><div className="dashboard-kicker"><span className="pulse-dot"/> {demo?"DEMO WORKSPACE":address?"LOCAL WALLET CONNECTED":"CONNECT WALLET TO CONTINUE"}</div><h1>{role==="Worker"?"Your work, protected.":"Your workforce, organized."}</h1><p>{role==="Worker"?"See the jobs attached to your wallet, the wage status and what needs to happen next.":"Post work, fund the escrow and keep every job milestone visible from one dashboard."}</p><div className="dashboard-actions"><Link className="btn btn-primary" href={role==="Worker"?"/jobs":"/jobs/new"}>{role==="Worker"?"Find more work":"Post a new job"}</Link><Link className="btn btn-ghost" href={role==="Worker" && target ? `/passport/${target}` : "/jobs"}>{role==="Worker" ? "Work Passport" : "Browse jobs"}</Link></div></div><div className="role-visual"><div className="role-visual-top"><span>{role.toUpperCase()} VIEW</span><span className="shield">✓</span></div><div className="visual-number">{String(relevant.length).padStart(2,"0")}</div><div className="visual-caption">jobs on this dashboard</div><div className="visual-line"><span/> WageEscrow lifecycle</div></div></section>
<section className="role-switcher-wrap"><div className="role-switcher-label"><Eyebrow>DASHBOARD ROLE</Eyebrow><span>Switch the view to match how you use Wagely.</span></div><div className="role-switcher">{roles.map(r=><button key={r} className={role===r?"selected":""} onClick={()=>choose(r)}><span className="role-icon">{r[0]}</span><span><strong>{r}</strong><small>{r==="Worker"?"Work & wages":"Jobs & escrow"}</small></span></button>)}</div></section>
<section className="stat-cards">{role==="Worker"?<><Stat label="Active jobs" value={stats.active} note="Funded or in progress"/><Stat label="Awaiting action" value={stats.claimed} note="Completion claimed" accent/><Stat label="Completed" value={stats.completed} note="Payment released"/><Stat label="Funded" value={stats.funded} note="Escrow active"/></>:<><Stat label="Jobs posted" value={relevant.length} note="On your dashboard"/><Stat label="Escrow active" value={stats.funded} note="Funded jobs" accent/><Stat label="Awaiting approval" value={stats.claimed} note="Completion claimed"/><Stat label="Released" value={stats.completed} note="Payment released"/></>}</section>
{error&&<div className="alert error mb-5">{error}</div>}{!demo&&!address&&<EmptyState title="Connect a wallet" text="Use MetaMask on the local Hardhat network, or switch Demo on in the header."/>}{!demo&&address&&!isLocal(chainId)&&<EmptyState title="Switch to Local Hardhat" text="The current Wagely frontend is configured for the team's local Hardhat network."/>}{(demo||(address&&isLocal(chainId)))&&<><div className="section-row-head"><div><Eyebrow>{role==="Worker"?"MY WORK":"MY JOBS"}</Eyebrow><h2>{role==="Worker"?"Your protected work":"Your active workforce"}</h2></div><span className="result-count">{relevant.length} record{relevant.length===1?"":"s"}</span></div>{relevant.length?<div className="job-grid">{relevant.map(j=><JobCard key={j.id} job={j} meta={demo?j:getJobMeta(j.id)}/>)}</div>:<EmptyState title={role==="Worker"?"No work on this wallet":"No jobs posted yet"} text={role==="Worker"?"When a contractor posts a job for this wallet it will appear here.":"Create your first protected job and fund the escrow."} action={role==="Contractor"?<Link className="btn btn-primary" href="/jobs/new">Post your first job</Link>:undefined}/>}</>}
<section className="dashboard-bottom-grid"><Card className="activity-card"><Eyebrow>WAGELY BASICS</Eyebrow><div className="feature-row"><span>01</span><div><strong>Fund before the work starts</strong><p>The contractor locks the agreed amount in the escrow contract.</p></div></div><div className="feature-row"><span>02</span><div><strong>Keep the state visible</strong><p>Created, Funded, Started, Completion Claimed and Released are shown directly.</p></div></div><div className="feature-row"><span>03</span><div><strong>Use the contract, not a promise</strong><p>Actions are tied to the wallet role and the on-chain job state.</p></div></div></Card><Card className="quick-card"><Eyebrow>QUICK ACTION</Eyebrow><h2>{role==="Worker"?"Find your next job.":"Create protected work."}</h2><p>{role==="Worker"?"Browse the marketplace-style job list and open any job to see the wage and lifecycle.":"Add the job details, worker and supervisor, then post it to the local contract."}</p><Link className="quick-link" href={role==="Worker"?"/jobs":"/jobs/new"}>{role==="Worker"?"Find work":"Post a job"}<span>→</span></Link></Card></section>
</div></main>}
function Stat({label,value,note,accent=false}:{label:string;value:React.ReactNode;note:string;accent?:boolean}){return <div className={`stat-card ${accent?"accent":""}`}><span>{label}</span><strong>{value}</strong><small>{note}</small></div>}
